# Importing Libs

In [5]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

model=DecisionTreeRegressor(random_state=1)

# **Importing the DataSet**

In [13]:
df=pd.read_csv('Breast_cancer_data.csv')
df

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0
1,20.57,17.77,132.90,1326.0,0.08474,0
2,19.69,21.25,130.00,1203.0,0.10960,0
3,11.42,20.38,77.58,386.1,0.14250,0
4,20.29,14.34,135.10,1297.0,0.10030,0
...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0
565,20.13,28.25,131.20,1261.0,0.09780,0
566,16.60,28.08,108.30,858.1,0.08455,0
567,20.60,29.33,140.10,1265.0,0.11780,0
568,7.76,24.54,47.92,181.0,0.05263,1

# Selecting Value And Features For the Model

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y , test_size=5, random_state=1)

In [17]:
X_train

     mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
132        16.16         21.54          106.20      809.8          0.10080
161        19.19         15.94          126.30     1157.0          0.08694
197        18.08         21.84          117.40     1024.0          0.07371
245        10.48         19.86           66.72      337.7          0.10700
453        14.53         13.98           93.86      644.2          0.10990
..           ...           ...             ...        ...              ...
129        19.79         25.12          130.40     1192.0          0.10150
144        10.75         14.97           68.26      355.3          0.07793
72         17.20         24.52          114.20      929.4          0.10710
235        14.03         21.25           89.79      603.4          0.09070
37         13.03         18.42           82.61      523.8          0.08983

[564 rows x 5 columns]

In [18]:
model.fit(X_train,y_train)

DecisionTreeRegressor(random_state=1)

In [31]:
X_test

     mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
421        14.69         13.98           98.22      656.1          0.10310
47         13.17         18.66           85.98      534.6          0.11580
292        12.95         16.02           83.14      513.7          0.10050
186        18.31         18.58          118.60     1041.0          0.08588
414        15.13         29.81           96.71      719.5          0.08320

In [39]:
df.columns[2]

'mean_perimeter'

In [41]:
inputs=[]

for i in range(5):
  inputs.append(input('Please Enter '+df.columns[i]+" "))

Please Entermean_radius 123
Please Entermean_texture 123
Please Entermean_perimeter 123
Please Entermean_area 123
Please Entermean_smoothness 12333

In [43]:
X_predict=model.predict([inputs])
print(X_predict)

[0.]

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"

In [36]:
xt=pd.read_csv('Breast_cancer_data.csv')
xt.iloc[[47]]

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,diagnosis
47,13.17,18.66,85.98,534.6,0.1158,0